unexpectedjs/unexpected-dom

lib/index.js, package.json, test/unexpected-dom.js
Work in progress. Tests are failing
=> To have attributes object

lib/index.js, test/unexpected-dom.js
This makes all the regular 'object' assertions work for the types defined by unexpected-dom.
=> Set HTMLElement's base type to DOMNode, and DOMNode's base type to object

lib/index.js, test/unexpected-dom.js
The `identify` function of `HTMLDocument` should probably be improved, but I had a little trouble understanding the overall strategy for detecting these instances in both the browser and jsdom.
`queried for` is the spike I mentioned on the unexpected gitter. It's one out of many possible takes on how to add querying support.
=> Html document type and "queried for" assertion

test/unexpected-dom.js
Avoids touching err.output so that we're ready for Unexpected 8.
=> Test suite: Simplify usage of 'to throw'.

lib/index.js, package.json
... and be compatible with promise-returning `expect.it` assertions in 'to satisfy' specs.
=> Update unexpeted to 7.0.1

lib/index.js, test/unexpected-dom.js
/cc @sunesimonsen who came up with the idea of doing the diff like this.
Next thing I'd like to look into is a `to satisfy` for `HTMLElement`, but this PR is already too big.
=> Implemented diff for 'to have attributes' + to have class(es) assertion

lib/index.js, package.json, test/unexpected-dom.js
For some reason it was never possible to assert that an attribute is absent by going:
```js
expect(element, 'to have attributes', { foo: undefined });
// or:
expect(element, 'to satisfy', { attributes: { foo: undefined } });
```
Analogous to the object `to satisfy` semantics.
This PR fixes that and adds tests.
=> Expect attribute to be absent

lib/index.js
This change is completely backwards compatible, but will prepare the project for the upcoming unexpected v9 release.
=> Make unexpected-dom forward compatible with unexpected v9

README.md, lib/index.js, test/unexpected-dom.js
This is a variant of the 'to have no elements matching',
via a flag. 
README.md updated with examples, and included
examples of 'to have children', as that was also 
undocumented.
=> Add 'to have elements matching' assertion

lib/index.js, package.json, test/unexpected-dom.js
=> To satisfy against DOMElement/string

lib/index.js
We might need a way to tolerate whitespace difference and the like, but in any case, this is not the correct way to accomplish that.
As per the discussion on the Unexpected gitter channel.
=> Consider surrounding whitespace when comparing text nodes for equality

lib/index.js, test/unexpected-dom.js
DOMElement equal: Made node name comparisons case sensitive in XML documents.
Fixes #32.
=> Fixed detection of HTML/XML in Safari and IE.

package.json
:rocket:
unexpected just published version 9.16.1, so that’s now up to date in your `package.json`.
Check that it doesn’t break your code and release the new version of your software safe in the knowledge that it will stay in this working state.
---
The new version differs by 9 commits (ahead by 9, behind by 0).
- [b48b73f](https://github.com/unexpectedjs/unexpected/commit/b48b73f7c751f1957ea787963c92156b18a67610): 9.16.1
- [5a70595](https://github.com/unexpectedjs/unexpected/commit/5a705952ceca6a529e6cf2786624fe52c9fd9280): Build unexpected.js
- [f79fb19](https://github.com/unexpectedjs/unexpected/commit/f79fb19884f4beb46e539dd86793a04de08ce042): Makefile: node_modules/.bin/deploy-site{ => .sh}
- [c2454fd](https://github.com/unexpectedjs/unexpected/commit/c2454fd9ba0625cfbeb54e4fcedec52c4 …
=> Updated unexpected to version 9.16.1

lib/index.js, package.json, test/unexpected-dom.js
Cuts compatibility with Unexpected 9 and below, sorry.
Bonus features:
* when parsed as, when queried for: Make 'when' optional and provide the result as the fulfillment value if no assertion is provided.
* Add support for satisfying DOMNodeList against strings and DOMNodeList. Exploit it to support `expect(domElement, 'to satisfy', children: 'foo<span>bar</span>');`
* queried for: Don't put CSS selectors in quotes in the error messages
=> Update to Unexpected 10

package.json, test/unexpected-dom.js
Also update unexpected-sinon and start using the `to have calls satisfying` assertion.
=> Update unexpected to 10.5

lib/index.js, test/unexpected-dom.js
=> Implement <DOMTextNode> to [exhaustively] satisfy <regexp>

README.md, lib/index.js, test/unexpected-dom.js
This is useful to testing that a button is not disabled.
```js
expect(button, 'not to have attribute', 'disabled')
```
=> Added a `not to have (attribute|attributes)` assertion.

.eslintignore, .eslintrc.js, .prettierignore, .prettierrc, lib/index.js, lib/matchesSelector.js, package.json, test/jsdom-compatibility.js, test/unexpected-dom.js
This is a the same kind of setup we have in unexpected.
=> Added a prettier setup

lib/index.js, test/unexpected-dom.js
When `to contain elements matching` fails you usually don't get the details you need as the inspected output dot out sub trees deeper than 3 levels.
=> Fully inspect subject when contain elements matching fails

lib/index.js, test/unexpected-dom.js
You need to use a special comment `` on the rhs. That was the least intrusive solution I could come up with. Using an `<ignore/>` element does not work as it is not a void element, so you would have to type `<ignore></ignore>` - that is a little too much ignore :-)
=> Support ignoring subtrees in to satisfy

lib/index.js, test/index.spec.js
This is useful for testing React components with unexpected-dom as you can't
produce a comment in JSX.
This is still a feature (undocumented) until I have tested it in real
applications.
=> Add support for an ignore tag in addition to the ignore tag

lib/index.js
When using the top-level expect instead of the wrapped expect, we will end up serializing errors that we shouldn't. This PR make sure that we will use the wrapped expect instead.
=> Remove the top-level expect

lib/index.js, test/index.spec.js
Fixes: #212
Reproduces a bug where the user is trying to ignore a text node in to satisfy and fixes it.
=> Fix: Ignore bug

lib/index.js, test/index.spec.js
The dragabble attribute was not being correctly recognised - when
specified it must have only two values, the strings "true" and
"false". Previously it was treated as a boolean attribute, which
lead to true being accepted while false did not work at all.
Change this so the only acceptable values are the two supported
strings. Add some belt and braces when specifying the value in an
object spec so you cannot accidentally specify an unsupported value.
=> Fix the draggable attribute & flesh out enumerated property support.

lib/index.js, test/index.spec.js
Fixes `` as the top-level to satisfy RHS.
=> Model <!--ignore--> as its own type and implement the ignoring via an assertion

lib/index.js, test/index.spec.js
This is a backwards compatible version of the previous PR that ensures that any DOMNode present in the `children` property of an object spec is converted before comparison.
Fixes https://github.com/unexpectedjs/unexpected-dom/issues/217.
=> Fix comment nodes being specified as children in a satisfy spec.

lib/index.js, test/index.spec.js
We currently ignore empty styles in RHS which is quite surprising. This PR
fixes it by validating the RHS styles.
=> Fix: Validate style attributes on the RHS

.eslintignore, src/index.js, src/matchesSelector.js, test/index.spec.js, test/jsdom-compatibility.js
=> Modernize the codebase

src/index.js, test/index.spec.js
Patch to the recently introduced style names validation.
=> Allow dashes in style names and values

documentation/assertions/DOMElement/to-contain.md, documentation/assertions/DOMNodeList/to-contain.md, src/index.js, test/index.spec.js
=> <DOMDocument|DOMElement|DOMDocumentFragment> [not] to contain <DOMElement|object>

documentation/assertions/DOMElement/queried-for-test-id.md, documentation/assertions/DOMElement/queried-for.md, documentation/assertions/DOMElement/to-contain-elements-matching.md, documentation/assertions/DOMElement/to-contain-test-id.md, documentation/assertions/DOMElement/to-have-test-id.md, src/index.js, test/index.spec.js
It is becoming a recognised pattern for DOM testing to use test id's on elements. 
Test id's is just a adding a `data-test-id` attribute to elements so you have a stable way of finding them from your tests.
We can already handle those, but it is kind of inconvenient and given how often it is used, I think we should add first class support for the concept. 
Fixes: #285
=> First class support for test id's

documentation/assertions/DOMElement/to-contain.md, documentation/assertions/DOMElement/to-satisfy.md, src/index.js, test/index.spec.js
Fixes https://github.com/unexpectedjs/unexpected-dom/issues/294
=> Fix weird output :)

src/index.js, test/index.spec.js
Add support for an expect.it() to level to "to satisfy" but disallow it at the top-level of "to contain".
=> Support for expect.it

src/index.js, test/index.spec.js
We are currently going into infinite recursion if you compare a DOMDocumentFragment with a DOMElement. 
I special cases those comparisons to fail.
=> Fix infinite recursion for edge-case comparison

package.json, test/assertions/to-satisfy.spec.js
An alternative change to magicpen put together by @papandreou after we discussed many alternatives. This PR shows that using it we can swap back to `installTheme()` in `magicpen-prism` (https://github.com/unexpectedjs/magicpen-prism/pull/5) while continue to serlialise correctly in nested assertions.
=> Clone aware magic pen themes

src/index.js, test/index.spec.js
This adds a `:focus` indicator inside an elements start tag in the inspection output if the element is currently focused.
The `<body>` tag is explicitly exempt from this addition, since it is the initial focus element and would likely add surprising output to tests that do not deal with moving focus around.
Example output:
```html
<div role="tablist">
<button id="tabs-1-0" aria-selected="true" role="tab" tabindex="0">...</button>
<button id="tabs-1-1" aria-selected="false" role="tab" tabindex="-1">...</button>
<button id="tabs-1-2" aria-selected="false" role="tab" tabindex="-1" :focus>...</button>
</div>
```
See focus testing thread starting at https://gitter.im/unexpectedjs/unexpected?at=5eba63cbfaa128031cc7f9e2
=> Add ':focus' indicator in element start tag

bootstrap-unexpected-markdown.js, documentation/assertions/DOMElement/to-contain-focused-element-matching.md, documentation/assertions/DOMElement/to-have-focus.md, src/index.js, test/assertions/to-contain-focused-element-matching.js, test/assertions/to-have-focus.js
This adds a new convenience assertion to help with testing focus management.
```js
const component = mount(<Tabs tabs={tabs} defaultTab={0} />);
simulate(component, {
type: "keyDown",
target: '[role="tablist"]',
data: {
key: "End"
}
});
expect(component, "to contain focused element matching", '[role="tab"]:nth-child(2)');
```
**Output with focus not even inside `component`**:
**Output with the wrong element focused**:
=> Add 'DOMElement to contain focused element' assertion

src/index.js, test/assertions/to-satisfy.spec.js
We forgot to pass on the `exhaustively` flag.
=> Fix to exhaustively satisfy for node lists
